//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallRecord
    {
        public long call_id { get; set; }
        public string cust_id { get; set; }
        public long user_id { get; set; }
        public System.DateTime call_day { get; set; }
        public System.DateTime call_time { get; set; }
        public bool available { get; set; }
        public string last_name { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
