//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.CallRecords = new HashSet<CallRecord>();
        }
    
        public long user_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
    
        public virtual ICollection<CallRecord> CallRecords { get; set; }
    }
}
